[package]
name = "link"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenvy = "0.15.7"
r2d2 = "0.8.10"
redis = "0.25.3"
diesel = { version = "2", features = ["sqlite", "r2d2", "uuid"] }

